theme: minima
title: El blog de Noe
author: GitNoe
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Blog de prueba creado con Github Pages y Jekyll mediante un tutorial de Learning Lab.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
